services:
  # --- The main Rasa Server ---
  - name: rasa-server
    type: web
    env: docker
    plan: free
    dockerfilePath: ./rasa-server.Dockerfile
    healthCheckPath: /
    # This startCommand is the definitive fix for the 404 error
    startCommand: "rasa run --enable-api --cors '*' --credentials credentials.yml --endpoints endpoints.yml --connector telegram"
    envVars:
      - fromGroup: rasa-secrets
  # --- The Rasa Action Server ---
  - name: action-server
    type: web
    env: docker
    plan: free
    dockerfilePath: ./action-server.Dockerfile