services:
  # --- The main Rasa Server ---
  - name: rasa-server
    type: web
    env: docker
    plan: free
    dockerfilePath: ./rasa-server.Dockerfile
    healthCheckPath: /
    envVars:
      - fromGroup: rasa-secrets
  # --- The Rasa Action Server ---
  - name: action-server
    type: web
    env: docker
    plan: free
    dockerfilePath: ./action-server.Dockerfile